### ISSUE TITLE
不能用了

### ISSUE THREAD

**Issue by xc4567132** [DouchChunFeng/MoGuDing-WinForm#1]
不能用了！

**Comment by DouchChunFeng** [comment]
你好，已经更新，请下载debug中的1.1.3.0。

**Comment by xc4567132** [comment]
我不知道在哪里下载，能不能加一下你的联系方式

**Comment by xc4567132** [comment]
QQ  565740350

**Comment by DouchChunFeng** [comment]
https://github.com/DouchChunFeng/MoGuDing-WinForm/releases/download/1.1.3.0/MGD_20231116.exe

**Comment by xc4567132** [comment]
谢谢，能不能加一下我qq，有事咨询

**Comment by xc4567132** [comment]
谢谢，能不能加一下我qq，有事咨询  565740350

**Comment by xc4567132** [comment]
有事咨询 565740350
