### ISSUE TITLE
Token变化后导致打卡失效

### ISSUE THREAD

**Issue by TttRark** [DouchChunFeng/MoGuDing-WinForm#2]
工学云好像只支持单设备，每次登上查看签到后软件会打卡失败，但是日志中还是显示打卡成功，查看软件内没有打卡记录。

**Comment by DouchChunFeng** [comment]
你好，提供下显示打卡成功但没有记录的日志呗。
你说的单设备确实是这样子的，如果要共用token得你去手机上抓token然后粘贴到软件里的登录信息txt里

**Comment by DouchChunFeng** [comment]
日志显示成功是服务器给的反馈码的，请再检查一下?

**Comment by DouchChunFeng** [comment]
目前都是测试正常的
![test1](https://github.com/DouchChunFeng/MoGuDing-WinForm/assets/84675621/4d13db5b-4a07-41d5-8e63-e99214f40c09)

**Comment by DouchChunFeng** [comment]
测试正常，长时间未继续反馈，关闭本issue
